sudo: false

language: python

env:
  - PYTHON_VERSION=2.7.11
  - PYTHON_VERSION=3.4.4
  - PYTHON_VERSION=3.5.1

addons:
  apt:
    sources:
      # Debian sid currently holds OpenSSL 1.0.2
      - debian-sid
    packages:
      - libssl-dev

cache:
  pip: true
  directories:
    - $HOME/env
    - $HOME/.pyenv

install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh

after_success:
  - ./.travis/after.sh

notifications:
  email:
    on_success: never
    on_failure: change
